# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [125]:
# Importing Libraries

import numpy as np

num = 6*np.ones((5,5),dtype=int)
print('Original array')
print(num)
print('\n0 inside 2D array')

num[1:-1,1:-1] = 0
print(num)


Original array
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

0 inside 2D array
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [47]:
x = 9*np.ones((3,3))
print("Checkerboard pattern:")
x = 3*np.ones((8,8),dtype=int)
x[1::2,::2] = 9
x[::2,1::2] = 9
print(x)


Checkerboard pattern:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [57]:
num = np.empty((4,3))
print(' First Output')
print(num)

num1=6*np.ones((3,3),dtype = int)
print('\nSecond Output')
print(num1)


 First Output
[[1.42685456e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.44922912e+169]
 [1.18997250e-047 6.27831253e+174 8.61658426e-043]
 [1.32791550e-075 9.27982548e-072 1.79821557e-052]]

Second Output
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [60]:
values = [0,12,45.21,34,99.91]
x = np.array(values)
print('Fahrenheit degree values: ')
print(x)
print('\nCentigrade values: ')
print(5*x/9 - 5*32/9)

Fahrenheit degree values: 
[ 0.   12.   45.21 34.   99.91]

Centigrade values: 
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [81]:
num = np.sqrt([1+0j])
num2 = np.sqrt([0+1j])
print('Original array:{}{}' .format(num,num2))
print('''\nReal part of thr array: 
{}{}'''.format(num.real,num2.real))
print('''\nImaginary part of the array:
{}{}'''.format(num.imag, num2.imag))



Original array:[1.+0.j][0.70710678+0.70710678j]

Real part of thr array: 
[1.][0.70710678]

Imaginary part of the array:
[0.][0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [108]:
Array1 = [0,10,20,40,60]
Array2 = [0,40]
print('Array1 :', array1)
print('Array2 :', array2)
print('\nCompare each element of Array1 and Arrar2')
print(np.in1d(Array1,Array2))


Array1 : [0, 10, 20, 40, 60]
Array2 : [0, 40]

Compare each element of Array1 and Arrar2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]
    

In [109]:
Array1 = [0,10,20,40,60]
Array2 = [0,40]
print('Array1 :', array1)
print('Array2 :', array2)
print('\nCommon values between two arrays')
print(np.intersect1d(Array1,Array2))

Array1 : [0, 10, 20, 40, 60]
Array2 : [0, 40]

Common values between two arrays
[ 0 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [112]:
Array1 = np.array([10,10,20,20,30])
Array2 = np.array([[1,1],[2,3]])
print('Original array:')
print(Array1)
print('\nUnique elements of the above array:')
print(np.unique(Array1))
print('\nOriginal array:')
print(Array2)
print('\nUnique elements of the above array:')
print(np.unique(Array2))


Original array:
[10 10 20 20 30]

Unique elements of the above array:
[10 20 30]

Original array:
[[1 1]
 [2 3]]

Unique elements of the above array:
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [111]:
Array1= np.array([ 0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70])
print('\nOriginal array:')
print('Arrray1 :', Array1)
print('\nOriginal array:')
print('Arrray1 :', Array2)
print('\nUnique values that are in only one (not both) of the input arrays')
print(np.setxor1d(Array1,Array2))



Original array:
Arrray1 : [ 0 10 20 40 60 80]

Original array:
Arrray1 : [10 30 40 50 70]

Unique values that are in only one (not both) of the input arrays
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [113]:
np.all([[True,False],[True,True]])

False

Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [114]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [115]:
Array = np.array([1,2,3,4])
print('Original array:')
print(Array)
print('\nRepeating 2 times:')
print(np.tile(Array,2))
print('\n Repeating 3 times:')
print(np.tile(Array,3))

Original array:
[1 2 3 4]

Repeating 2 times:
[1 2 3 4 1 2 3 4]

 Repeating 3 times:
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [119]:
Array = np.array([1,2,3,4,5,6])
print('Original array: {}'.format(Array))
print('Maximum Values: {}'.format(np.argmax(Array)))
print('Minimum Values: {}'.format(np.argmin(Array)))

Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [4]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))


Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [21]:
Array = np.array([[4,6],[2,1]])
print('Original array: ')
print(Array)
print('\n Sort along the first axis: ')
print(np.sort(Array, axis=0))
print('\n Sort along the last axis: ')
print(np.sort(Array, axis=1))


Original array: 
[[4 6]
 [2 1]]

 Sort along the first axis: 
[[2 1]
 [4 6]]

 Sort along the last axis: 
[[4 6]
 [1 2]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [24]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)


[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [25]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("\nValues bigger than 10 =", x[x>10])
print("\nTheir indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]

Values bigger than 10 = [20 20 30 40]

Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [29]:
Bytes = np.zeros((4,4))
print("%d bytes" % (Bytes.size * Bytes.itemsize))


128 bytes


## Great Job!